# Generated by Django 4.2.3 on 2023-07-11 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("apicius", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userreview",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="step",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="steps",
                to="apicius.recipe",
            ),
        ),
        migrations.AddField(
            model_name="recipeingredient",
            name="ingredient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="apicius.ingredient"
            ),
        ),
        migrations.AddField(
            model_name="recipeingredient",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="apicius.recipe"
            ),
        ),
        migrations.AddField(
            model_name="recipecookingtime",
            name="cooking_time",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="apicius.cookingtime"
            ),
        ),
        migrations.AddField(
            model_name="recipecookingtime",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="apicius.recipe"
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="author_recipes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="cooking_times",
            field=models.ManyToManyField(
                through="apicius.RecipeCookingTime", to="apicius.cookingtime"
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="favorites",
            field=models.ManyToManyField(
                blank=True, related_name="user_favorites", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="ingredients",
            field=models.ManyToManyField(
                related_name="recipes",
                through="apicius.RecipeIngredient",
                to="apicius.ingredient",
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="recipe_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="apicius.recipetype"
            ),
        ),
    ]
