# Generated by Django 4.2.3 on 2023-07-11 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("apicius", "0003_alter_cookingtime_options_alter_ingredient_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userreview",
            name="user",
        ),
        migrations.AddField(
            model_name="userreview",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="apicius.author",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="author_recipes",
                to="apicius.author",
                verbose_name="author",
            ),
        ),
    ]
