# Generated by Django 4.2.3 on 2023-07-11 10:16

import authuser.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("authuser", "0001_initial"),
        ("apicius", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cookingtime",
            options={
                "verbose_name": "cooking_time",
                "verbose_name_plural": "cooking_times",
            },
        ),
        migrations.AlterModelOptions(
            name="ingredient",
            options={"verbose_name": "ingredient"},
        ),
        migrations.AlterModelOptions(
            name="recipe",
            options={"verbose_name": "recipe"},
        ),
        migrations.AlterModelOptions(
            name="recipecookingtime",
            options={"verbose_name": "recipe_cooking_time"},
        ),
        migrations.AlterModelOptions(
            name="recipeingredient",
            options={"verbose_name": "recipe_ingredient"},
        ),
        migrations.AlterModelOptions(
            name="recipetype",
            options={"verbose_name": "recipe_type"},
        ),
        migrations.AlterModelOptions(
            name="step",
            options={"verbose_name": "step"},
        ),
        migrations.AlterModelOptions(
            name="userreview",
            options={"verbose_name": "user_review"},
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="favorites",
        ),
        migrations.AlterField(
            model_name="recipe",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="author_recipes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="author",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="cooking_times",
            field=models.ManyToManyField(
                through="apicius.RecipeCookingTime",
                to="apicius.cookingtime",
                verbose_name="cooking_times",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="ingredients",
            field=models.ManyToManyField(
                related_name="recipes",
                through="apicius.RecipeIngredient",
                to="apicius.ingredient",
                verbose_name="ingredients",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="recipe_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="apicius.recipetype",
                verbose_name="recipe_type",
            ),
        ),
        migrations.AlterField(
            model_name="recipecookingtime",
            name="cooking_time",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="apicius.cookingtime",
                verbose_name="cooking_time",
            ),
        ),
        migrations.AlterField(
            model_name="recipecookingtime",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="apicius.recipe",
                verbose_name="recipe",
            ),
        ),
        migrations.AlterField(
            model_name="step",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="steps",
                to="apicius.recipe",
                verbose_name="recipe",
            ),
        ),
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "favorite_recipes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="user_favorites",
                        to="apicius.recipe",
                        verbose_name="favorites",
                    ),
                ),
            ],
            options={
                "verbose_name": "author",
            },
            bases=("authuser.user",),
            managers=[
                ("objects", authuser.models.CustomUserManager()),
            ],
        ),
    ]
