# Generated by Django 4.2.3 on 2024-01-31 22:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("apicius", "0004_remove_userreview_user_userreview_author_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created_at",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="author",
            name="slug",
            field=models.SlugField(null=True, verbose_name="slug"),
        ),
        migrations.AddField(
            model_name="author",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="updated_at"),
        ),
        migrations.AddField(
            model_name="cookingtime",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created_at",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cookingtime",
            name="slug",
            field=models.SlugField(null=True, verbose_name="slug"),
        ),
        migrations.AddField(
            model_name="cookingtime",
            name="slug_en",
            field=models.SlugField(null=True, verbose_name="slug"),
        ),
        migrations.AddField(
            model_name="cookingtime",
            name="slug_fr",
            field=models.SlugField(null=True, verbose_name="slug"),
        ),
        migrations.AddField(
            model_name="cookingtime",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="updated_at"),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created_at",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ingredient",
            name="slug",
            field=models.SlugField(null=True, verbose_name="slug"),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="slug_en",
            field=models.SlugField(null=True, verbose_name="slug"),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="slug_fr",
            field=models.SlugField(null=True, verbose_name="slug"),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="updated_at"),
        ),
        migrations.AddField(
            model_name="recipe",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created_at",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="recipe",
            name="slug",
            field=models.SlugField(null=True, verbose_name="slug"),
        ),
        migrations.AddField(
            model_name="recipe",
            name="slug_en",
            field=models.SlugField(null=True, verbose_name="slug"),
        ),
        migrations.AddField(
            model_name="recipe",
            name="slug_fr",
            field=models.SlugField(null=True, verbose_name="slug"),
        ),
        migrations.AddField(
            model_name="recipe",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="updated_at"),
        ),
        migrations.AddField(
            model_name="recipetype",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created_at",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="recipetype",
            name="slug",
            field=models.SlugField(null=True, verbose_name="slug"),
        ),
        migrations.AddField(
            model_name="recipetype",
            name="slug_en",
            field=models.SlugField(null=True, verbose_name="slug"),
        ),
        migrations.AddField(
            model_name="recipetype",
            name="slug_fr",
            field=models.SlugField(null=True, verbose_name="slug"),
        ),
        migrations.AddField(
            model_name="recipetype",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="updated_at"),
        ),
    ]
