# Generated by Django 4.2.3 on 2024-01-31 23:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apicius", "0005_author_created_at_author_slug_author_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="slug"),
        ),
        migrations.AlterField(
            model_name="cookingtime",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="slug"),
        ),
        migrations.AlterField(
            model_name="cookingtime",
            name="slug_en",
            field=models.SlugField(null=True, unique=True, verbose_name="slug"),
        ),
        migrations.AlterField(
            model_name="cookingtime",
            name="slug_fr",
            field=models.SlugField(null=True, unique=True, verbose_name="slug"),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="slug"),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="slug_en",
            field=models.SlugField(null=True, unique=True, verbose_name="slug"),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="slug_fr",
            field=models.SlugField(null=True, unique=True, verbose_name="slug"),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="slug"),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="slug_en",
            field=models.SlugField(null=True, unique=True, verbose_name="slug"),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="slug_fr",
            field=models.SlugField(null=True, unique=True, verbose_name="slug"),
        ),
        migrations.AlterField(
            model_name="recipetype",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="slug"),
        ),
        migrations.AlterField(
            model_name="recipetype",
            name="slug_en",
            field=models.SlugField(null=True, unique=True, verbose_name="slug"),
        ),
        migrations.AlterField(
            model_name="recipetype",
            name="slug_fr",
            field=models.SlugField(null=True, unique=True, verbose_name="slug"),
        ),
    ]
